# Generated by Django 3.2 on 2022-07-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='DDN',
        ),
        migrations.AddField(
            model_name='prospect',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='créeLe',
            field=models.DateField(auto_now_add=True),
        ),
    ]
