# Generated by Django 3.2 on 2022-07-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_event_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateField(),
        ),
    ]
