# Generated by Django 3.2 on 2022-07-25 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20220717_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Agent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='DateDeProspection',
            field=models.DateField(default=datetime.datetime(2022, 7, 25, 9, 2, 58, 792497)),
        ),
        migrations.AddField(
            model_name='event',
            name='DureeContratOffert',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='Proposition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='ResultatDeVisite',
            field=models.TextField(choices=[('Intéressé', 'Intéressé'), ('NonIntéressé', 'NonIntéressé'), ('A revoir', 'A revoir'), ('RemiseDeContrat', 'RemiseDeContrat'), ('Recommandation', 'Recommandation')], default='Evaluation'),
        ),
        migrations.AddField(
            model_name='event',
            name='TypeContratOffert',
            field=models.TextField(choices=[('Performance Retraite Plus', 'Performance Retraite Plus'), ('Mixte simple', 'Mixte Simple'), ('Mixte Dynamique', 'Mixte Dynamique'), ('Rente Education', 'Rente Education'), ('Capitalisation Individuelle', 'Capitalisation Individuelle')], default='Performance Retraite Plus'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('Pas contacté', 'Pas contacté'), ('A relancer', 'A relancer'), ('En cours', 'En cours'), ('Pas intéressé', 'Pas intéressé'), ('Dossier Annulé', 'Dossier Annulé'), ('Signé', 'Signé')], default='Pas contacté', max_length=25),
        ),
    ]
