# Generated by Django 3.2 on 2022-07-26 11:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20220725_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='TypeContratOffert',
        ),
        migrations.AlterField(
            model_name='event',
            name='DateDeProspection',
            field=models.DateField(default=datetime.datetime(2022, 7, 26, 13, 23, 42, 493880)),
        ),
        migrations.AlterField(
            model_name='event',
            name='DureeContratOffert',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='Proposition',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeContratOffert', models.TextField(blank=True, choices=[('Performance Retraite Plus', 'Performance Retraite Plus'), ('Mixte simple', 'Mixte Simple'), ('Mixte Dynamique', 'Mixte Dynamique'), ('Rente Education', 'Rente Education'), ('Capitalisation Individuelle', 'Capitalisation Individuelle')], default='Performance Retraite Plus')),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.event')),
            ],
        ),
    ]
