# Generated by Django 3.2 on 2022-07-26 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20220726_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='TypeContratOffert',
            field=models.TextField(blank=True, choices=[('Performance Retraite Plus', 'Performance Retraite Plus'), ('Mixte simple', 'Mixte Simple'), ('Mixte Dynamique', 'Mixte Dynamique'), ('Rente Education', 'Rente Education'), ('Capitalisation Individuelle', 'Capitalisation Individuelle')], default='Performance Retraite Plus'),
        ),
        migrations.AlterField(
            model_name='event',
            name='DateDeProspection',
            field=models.DateField(default=datetime.datetime(2022, 7, 26, 13, 24, 22, 61942)),
        ),
        migrations.DeleteModel(
            name='Offre',
        ),
    ]
